console.log(1 + 1)

try {
    hola()
} catch (error) {
    console.log('hubo un error')
}

console.log(1 + 1)